# fly.toml app configuration file generated for strangersync-core on 2026-04-22T01:36:47-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'strangersync-core'
primary_region = 'sjc'

[build]
  dockerfile = 'services/core-service/Dockerfile'

[env]
  PORT = '8000'
  STATIC_PATH = '/app/static'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
